// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.std.impl.__pointer;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.impl.allocator.PointerChar;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("std::__pointer<char, std::allocator<char>, std::allocator<char>, 1>::type")
@FFIGen
@CXXHead(
        system = "__memory/allocator_traits.h"
)
public interface TypeCharStdAllocatorCharStdAllocatorChar1 extends CXXPointer {
    @FFIExpr("{0}")
    PointerChar get();

    static TypeCharStdAllocatorCharStdAllocatorChar1 cast(final long __foreign_address) {
        try {
            Class<TypeCharStdAllocatorCharStdAllocatorChar1> clz = (Class<TypeCharStdAllocatorCharStdAllocatorChar1>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(TypeCharStdAllocatorCharStdAllocatorChar1.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static TypeCharStdAllocatorCharStdAllocatorChar1 cast(final FFIPointer __foreign_pointer) {
        return TypeCharStdAllocatorCharStdAllocatorChar1.cast(__foreign_pointer.getAddress());
    }
}
