// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.std.impl.vector;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.arrow.Array;
import io.v6d.std.allocator;
import io.v6d.std.impl.allocator.ConstPointerStdSharedPtrArrowArray;
import io.v6d.std.impl.allocator.ConstReferenceStdSharedPtrArrowArray;
import io.v6d.std.impl.allocator.PointerStdSharedPtrArrowArray;
import io.v6d.std.impl.allocator.ReferenceStdSharedPtrArrowArray;
import io.v6d.std.shared_ptr;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("std::vector<std::shared_ptr<arrow::Array>, std::allocator<std::shared_ptr<arrow::Array>>>::allocator_type")
@FFIGen
@CXXHead(
        system = "vector"
)
public interface AllocatorTypeStdSharedPtrArrowArrayStdAllocatorStdSharedPtrArrowArray extends CXXPointer {
    @FFIExpr("{0}")
    allocator<shared_ptr<Array>> get();

    @FFITypeAlias("std::shared_ptr<arrow::Array>")
    shared_ptr<Array> allocate(long __n);

    void deallocate(@FFITypeAlias("std::shared_ptr<arrow::Array>") shared_ptr<Array> __p, long __n);

    @CXXValue
    PointerStdSharedPtrArrowArray address(@CXXValue ReferenceStdSharedPtrArrowArray __x);

    @CXXValue
    ConstPointerStdSharedPtrArrowArray address(@CXXValue ConstReferenceStdSharedPtrArrowArray __x);

    @FFITypeAlias("std::shared_ptr<arrow::Array>")
    shared_ptr<Array> allocate(long __n, @FFITypeAlias("const void*") long arg1);

    long max_size();

    void destroy(@CXXValue PointerStdSharedPtrArrowArray __p);

    static AllocatorTypeStdSharedPtrArrowArrayStdAllocatorStdSharedPtrArrowArray cast(
            final long __foreign_address) {
        try {
            Class<AllocatorTypeStdSharedPtrArrowArrayStdAllocatorStdSharedPtrArrowArray> clz = (Class<AllocatorTypeStdSharedPtrArrowArrayStdAllocatorStdSharedPtrArrowArray>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(AllocatorTypeStdSharedPtrArrowArrayStdAllocatorStdSharedPtrArrowArray.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static AllocatorTypeStdSharedPtrArrowArrayStdAllocatorStdSharedPtrArrowArray cast(
            final FFIPointer __foreign_pointer) {
        return AllocatorTypeStdSharedPtrArrowArrayStdAllocatorStdSharedPtrArrowArray.cast(__foreign_pointer.getAddress());
    }
}
