// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.std.impl.vector;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.__wrap_iter;
import io.v6d.std.impl.__wrap_iter.IteratorTypeStdSharedPtrArrowRecordBatch;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("std::vector<std::shared_ptr<arrow::RecordBatch>, std::allocator<std::shared_ptr<arrow::RecordBatch>>>::iterator")
@FFIGen
@CXXHead(
        system = "vector"
)
public interface IteratorStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch extends CXXPointer {
    @FFIExpr("{0}")
    __wrap_iter<PointerStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch> get();

    @CXXValue
    IteratorTypeStdSharedPtrArrowRecordBatch base();

    static IteratorStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch cast(
            final long __foreign_address) {
        try {
            Class<IteratorStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch> clz = (Class<IteratorStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(IteratorStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static IteratorStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch cast(
            final FFIPointer __foreign_pointer) {
        return IteratorStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(IteratorStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch.class, true));
    }

    static IteratorStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch create() {
        return IteratorStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch.getFactory().create();
    }

    @FFIFactory
    @CXXHead(
            system = "vector"
    )
    interface Factory {
        IteratorStdSharedPtrArrowRecordBatchStdAllocatorStdSharedPtrArrowRecordBatch create();
    }
}
