// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.std;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFIGen
@FFITypeAlias("int")
@CXXHead(
        system = "cstdint"
)
public interface CInt extends CXXPointer {
    @FFIExpr("*{0}")
    int get();

    @FFIExpr("*{0} = (int){1}")
    void set(int value);

    static CInt cast(final long __foreign_address) {
        try {
            Class<CInt> clz = (Class<CInt>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(CInt.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static CInt cast(final FFIPointer __foreign_pointer) {
        return CInt.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(CInt.class, true));
    }

    static CInt create() {
        return CInt.getFactory().create();
    }

    @FFIFactory
    interface Factory {
        CInt create();
    }
}
