// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.std;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("ptrdiff_t")
@FFIGen
@CXXHead(
        system = "stddef.h"
)
public interface ptrdiff_t extends CXXPointer {
    @FFIExpr("(*{0})")
    long get();

    @FFIExpr("*{0} = (ptrdiff_t){1}")
    void set(long __value);

    static ptrdiff_t cast(final long __foreign_address) {
        try {
            Class<ptrdiff_t> clz = (Class<ptrdiff_t>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(ptrdiff_t.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static ptrdiff_t cast(final FFIPointer __foreign_pointer) {
        return ptrdiff_t.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(ptrdiff_t.class, true));
    }

    static ptrdiff_t create() {
        return ptrdiff_t.getFactory().create();
    }

    static ptrdiff_t create(long __value) {
        return ptrdiff_t.getFactory().create(__value);
    }

    @FFIFactory
    @CXXHead(
            system = "stddef.h"
    )
    interface Factory {
        ptrdiff_t create();

        ptrdiff_t create(long __value);
    }
}
