// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard.impl.converttoarrowtype;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.arrow.ArrayData;
import io.v6d.arrow.Int8Array;
import io.v6d.arrow.impl.numericarray.IteratorTypeArrowInt8Type;
import io.v6d.arrow.impl.numericarray.ValueTypeArrowInt8Type;
import io.v6d.std.shared_ptr;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::ConvertToArrowType<signed char>::ArrayType")
@FFIGen
@CXXHead("basic/ds/arrow_utils.h")
public interface ArrayTypeSignedChar extends CXXPointer {
    @FFIExpr("{0}")
    Int8Array get();

    ValueTypeArrowInt8Type raw_values();

    byte Value(long i);

    byte GetView(long i);

    @CXXValue
    IteratorTypeArrowInt8Type begin();

    @CXXValue
    IteratorTypeArrowInt8Type end();

    static ArrayTypeSignedChar cast(final long __foreign_address) {
        try {
            Class<ArrayTypeSignedChar> clz = (Class<ArrayTypeSignedChar>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(ArrayTypeSignedChar.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static ArrayTypeSignedChar cast(final FFIPointer __foreign_pointer) {
        return ArrayTypeSignedChar.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(ArrayTypeSignedChar.class, true));
    }

    static ArrayTypeSignedChar create(
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::ArrayData>") shared_ptr<ArrayData> data) {
        return ArrayTypeSignedChar.getFactory().create(data);
    }

    @FFIFactory
    @CXXHead("basic/ds/arrow_utils.h")
    interface Factory {
        ArrayTypeSignedChar create(
                @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::ArrayData>") shared_ptr<ArrayData> data);
    }
}
