// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.shared_ptr;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::BaseListArrayBaseBuilder")
@FFIGen
@CXXHead("basic/ds/arrow.vineyard.h")
public interface BaseListArrayBaseBuilder<ArrayType> extends ObjectBuilder, FFIPointer {
    @CXXValue
    @FFITypeAlias("std::shared_ptr<vineyard::Object>")
    shared_ptr<Object> _Seal(@CXXReference Client client);

    @CXXValue
    Status Build(@CXXReference Client client);

    static <ArrayType> BaseListArrayBaseBuilder<ArrayType> cast(Class<ArrayType> __arraytype,
            final long __foreign_address) {
        try {
            Class<BaseListArrayBaseBuilder<ArrayType>> clz = (Class<BaseListArrayBaseBuilder<ArrayType>>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(FFITypeFactory.makeParameterizedType(BaseListArrayBaseBuilder.class, __arraytype), true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static <ArrayType> BaseListArrayBaseBuilder<ArrayType> cast(Class<ArrayType> __arraytype,
            final FFIPointer __foreign_pointer) {
        return BaseListArrayBaseBuilder.cast(__arraytype, __foreign_pointer.getAddress());
    }

    static <ArrayType> Factory<ArrayType> getFactory(Class<ArrayType> __arraytype) {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(FFITypeFactory.makeParameterizedType(BaseListArrayBaseBuilder.class, __arraytype), true));
    }

    static <ArrayType> BaseListArrayBaseBuilder<ArrayType> create(Class<ArrayType> __arraytype,
            @CXXReference Client client) {
        return BaseListArrayBaseBuilder.getFactory(__arraytype).create(client);
    }

    static <ArrayType> BaseListArrayBaseBuilder<ArrayType> create(Class<ArrayType> __arraytype,
            @CXXReference BaseListArray<ArrayType> __value) {
        return BaseListArrayBaseBuilder.getFactory(__arraytype).create(__value);
    }

    static <ArrayType> BaseListArrayBaseBuilder<ArrayType> create(Class<ArrayType> __arraytype,
            @CXXReference shared_ptr<BaseListArray<ArrayType>> __value) {
        return BaseListArrayBaseBuilder.getFactory(__arraytype).create(__value);
    }

    @FFIFactory
    @CXXHead("basic/ds/arrow.vineyard.h")
    interface Factory<ArrayType> {
        BaseListArrayBaseBuilder<ArrayType> create(@CXXReference Client client);

        BaseListArrayBaseBuilder<ArrayType> create(@CXXReference BaseListArray<ArrayType> __value);

        BaseListArrayBaseBuilder<ArrayType> create(
                @CXXReference shared_ptr<BaseListArray<ArrayType>> __value);
    }
}
