// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.CDouble;
import io.v6d.std.shared_ptr;
import io.v6d.vineyard.impl.numericarraybuilder.ArrayTypeDouble;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::DoubleBuilder")
@FFIGen
@CXXHead("basic/ds/arrow.h")
public interface DoubleBuilder extends CXXPointer {
    @FFIExpr("{0}")
    NumericArrayBuilder<CDouble> get();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<vineyard::NumericArrayBuilder<double>::ArrayType>")
    shared_ptr<ArrayTypeDouble> GetArray();

    @CXXValue
    Status Build(@CXXReference Client client);

    static DoubleBuilder cast(final long __foreign_address) {
        try {
            Class<DoubleBuilder> clz = (Class<DoubleBuilder>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(DoubleBuilder.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static DoubleBuilder cast(final FFIPointer __foreign_pointer) {
        return DoubleBuilder.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(DoubleBuilder.class, true));
    }

    static DoubleBuilder create(@CXXReference Client client,
            @CXXValue @FFITypeAlias("std::shared_ptr<vineyard::NumericArrayBuilder<double>::ArrayType>") shared_ptr<ArrayTypeDouble> array) {
        return DoubleBuilder.getFactory().create(client, array);
    }

    @FFIFactory
    @CXXHead("basic/ds/arrow.h")
    interface Factory {
        DoubleBuilder create(@CXXReference Client client,
                @CXXValue @FFITypeAlias("std::shared_ptr<vineyard::NumericArrayBuilder<double>::ArrayType>") shared_ptr<ArrayTypeDouble> array);
    }
}
