// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::IdTypeEnum")
@FFIGen
@CXXHead("basic/ds/types.h")
public interface IdTypeEnum<T> extends FFIPointer {
    static <T> IdTypeEnum<T> cast(Class<T> __t, final long __foreign_address) {
        try {
            Class<IdTypeEnum<T>> clz = (Class<IdTypeEnum<T>>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(FFITypeFactory.makeParameterizedType(IdTypeEnum.class, __t), true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static <T> IdTypeEnum<T> cast(Class<T> __t, final FFIPointer __foreign_pointer) {
        return IdTypeEnum.cast(__t, __foreign_pointer.getAddress());
    }
}
