// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.CInt;
import io.v6d.std.shared_ptr;
import io.v6d.vineyard.impl.numericarraybuilder.ArrayTypeInt;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::Int32Builder")
@FFIGen
@CXXHead("basic/ds/arrow.h")
public interface Int32Builder extends CXXPointer {
    @FFIExpr("{0}")
    NumericArrayBuilder<CInt> get();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<vineyard::NumericArrayBuilder<int>::ArrayType>")
    shared_ptr<ArrayTypeInt> GetArray();

    @CXXValue
    Status Build(@CXXReference Client client);

    static Int32Builder cast(final long __foreign_address) {
        try {
            Class<Int32Builder> clz = (Class<Int32Builder>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(Int32Builder.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static Int32Builder cast(final FFIPointer __foreign_pointer) {
        return Int32Builder.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(Int32Builder.class, true));
    }

    static Int32Builder create(@CXXReference Client client,
            @CXXValue @FFITypeAlias("std::shared_ptr<vineyard::NumericArrayBuilder<int>::ArrayType>") shared_ptr<ArrayTypeInt> array) {
        return Int32Builder.getFactory().create(client, array);
    }

    @FFIFactory
    @CXXHead("basic/ds/arrow.h")
    interface Factory {
        Int32Builder create(@CXXReference Client client,
                @CXXValue @FFITypeAlias("std::shared_ptr<vineyard::NumericArrayBuilder<int>::ArrayType>") shared_ptr<ArrayTypeInt> array);
    }
}
