// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.CSignedChar;
import io.v6d.std.shared_ptr;
import io.v6d.vineyard.impl.numericarraybuilder.ArrayTypeSignedChar;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::Int8Builder")
@FFIGen
@CXXHead("basic/ds/arrow.h")
public interface Int8Builder extends CXXPointer {
    @FFIExpr("{0}")
    NumericArrayBuilder<CSignedChar> get();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<vineyard::NumericArrayBuilder<signed char>::ArrayType>")
    shared_ptr<ArrayTypeSignedChar> GetArray();

    @CXXValue
    Status Build(@CXXReference Client client);

    static Int8Builder cast(final long __foreign_address) {
        try {
            Class<Int8Builder> clz = (Class<Int8Builder>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(Int8Builder.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static Int8Builder cast(final FFIPointer __foreign_pointer) {
        return Int8Builder.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(Int8Builder.class, true));
    }

    static Int8Builder create(@CXXReference Client client,
            @CXXValue @FFITypeAlias("std::shared_ptr<vineyard::NumericArrayBuilder<signed char>::ArrayType>") shared_ptr<ArrayTypeSignedChar> array) {
        return Int8Builder.getFactory().create(client, array);
    }

    @FFIFactory
    @CXXHead("basic/ds/arrow.h")
    interface Factory {
        Int8Builder create(@CXXReference Client client,
                @CXXValue @FFITypeAlias("std::shared_ptr<vineyard::NumericArrayBuilder<signed char>::ArrayType>") shared_ptr<ArrayTypeSignedChar> array);
    }
}
