// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFILibrary;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.arrow.Array;
import io.v6d.std.CUnsignedChar;
import io.v6d.std.shared_ptr;
import io.v6d.std.unique_ptr;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::LargeBinaryArray")
@FFIGen
@CXXHead("basic/ds/arrow.vineyard.h")
public interface LargeBinaryArray extends CXXPointer {
    @FFIExpr("{0}")
    BaseBinaryArray<io.v6d.arrow.LargeBinaryArray> get();

    void Construct(@CXXReference ObjectMeta meta);

    void PostConstruct(@CXXReference ObjectMeta meta);

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::LargeBinaryArray>")
    shared_ptr<io.v6d.arrow.LargeBinaryArray> GetArray();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Array>")
    shared_ptr<Array> ToArray();

    CUnsignedChar GetBase();

    static LargeBinaryArray cast(final long __foreign_address) {
        try {
            Class<LargeBinaryArray> clz = (Class<LargeBinaryArray>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(LargeBinaryArray.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static LargeBinaryArray cast(final FFIPointer __foreign_pointer) {
        return LargeBinaryArray.cast(__foreign_pointer.getAddress());
    }

    @FFIGen
    @FFILibrary(
            value = "vineyard::BaseBinaryArray<arrow::LargeBinaryArray>",
            namespace = "vineyard::BaseBinaryArray<arrow::LargeBinaryArray>"
    )
    @CXXHead("basic/ds/arrow.vineyard.h")
    interface Library {
        Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

        @CXXValue
        @FFITypeAlias("std::unique_ptr<vineyard::Object>")
        unique_ptr<Object> Create();
    }
}
