// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.shared_ptr;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::NumericArrayBaseBuilder")
@FFIGen
@CXXHead("basic/ds/arrow.vineyard.h")
public interface NumericArrayBaseBuilder<T> extends ObjectBuilder, FFIPointer {
    @CXXValue
    @FFITypeAlias("std::shared_ptr<vineyard::Object>")
    shared_ptr<Object> _Seal(@CXXReference Client client);

    @CXXValue
    Status Build(@CXXReference Client client);

    static <T> NumericArrayBaseBuilder<T> cast(Class<T> __t, final long __foreign_address) {
        try {
            Class<NumericArrayBaseBuilder<T>> clz = (Class<NumericArrayBaseBuilder<T>>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(FFITypeFactory.makeParameterizedType(NumericArrayBaseBuilder.class, __t), true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static <T> NumericArrayBaseBuilder<T> cast(Class<T> __t, final FFIPointer __foreign_pointer) {
        return NumericArrayBaseBuilder.cast(__t, __foreign_pointer.getAddress());
    }

    static <T> Factory<T> getFactory(Class<T> __t) {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(FFITypeFactory.makeParameterizedType(NumericArrayBaseBuilder.class, __t), true));
    }

    static <T> NumericArrayBaseBuilder<T> create(Class<T> __t, @CXXReference Client client) {
        return NumericArrayBaseBuilder.getFactory(__t).create(client);
    }

    static <T> NumericArrayBaseBuilder<T> create(Class<T> __t,
            @CXXReference NumericArray<T> __value) {
        return NumericArrayBaseBuilder.getFactory(__t).create(__value);
    }

    static <T> NumericArrayBaseBuilder<T> create(Class<T> __t,
            @CXXReference shared_ptr<NumericArray<T>> __value) {
        return NumericArrayBaseBuilder.getFactory(__t).create(__value);
    }

    @FFIFactory
    @CXXHead("basic/ds/arrow.vineyard.h")
    interface Factory<T> {
        NumericArrayBaseBuilder<T> create(@CXXReference Client client);

        NumericArrayBaseBuilder<T> create(@CXXReference NumericArray<T> __value);

        NumericArrayBaseBuilder<T> create(@CXXReference shared_ptr<NumericArray<T>> __value);
    }

    @FFITypeAlias("vineyard::NumericArrayBaseBuilder<%s>::ArrayType")
    @FFIGen
    @CXXHead("basic/ds/arrow.vineyard.h")
    interface ArrayType<T> extends CXXPointer {
        static <T> ArrayType<T> cast(Class<T> __t, final long __foreign_address) {
            try {
                Class<ArrayType<T>> clz = (Class<ArrayType<T>>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(FFITypeFactory.makeParameterizedType(ArrayType.class, __t), true));
                return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
                return null;
            }
        }

        static <T> ArrayType<T> cast(Class<T> __t, final FFIPointer __foreign_pointer) {
            return ArrayType.cast(__t, __foreign_pointer.getAddress());
        }
    }
}
