// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFINameAlias;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.arrow.Array;
import io.v6d.std.shared_ptr;
import io.v6d.std.string;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::RecordBatchExtender")
@FFIGen
@CXXHead("basic/ds/arrow.h")
public interface RecordBatchExtender extends RecordBatchBaseBuilder, FFIPointer {
    long num_rows();

    @CXXValue
    Status AddColumn(@CXXReference Client client, @CXXReference string field_name,
            @CXXValue @FFITypeAlias("std::shared_ptr<arrow::Array>") shared_ptr<Array> column);

    @CXXValue
    @FFINameAlias("Build")
    Status Build_1(@CXXReference Client client);

    static RecordBatchExtender cast(final long __foreign_address) {
        try {
            Class<RecordBatchExtender> clz = (Class<RecordBatchExtender>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(RecordBatchExtender.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static RecordBatchExtender cast(final FFIPointer __foreign_pointer) {
        return RecordBatchExtender.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(RecordBatchExtender.class, true));
    }

    static RecordBatchExtender create(@CXXReference Client client,
            @CXXValue @FFITypeAlias("std::shared_ptr<vineyard::RecordBatch>") shared_ptr<RecordBatch> batch) {
        return RecordBatchExtender.getFactory().create(client, batch);
    }

    @FFIFactory
    @CXXHead("basic/ds/arrow.h")
    interface Factory {
        RecordBatchExtender create(@CXXReference Client client,
                @CXXValue @FFITypeAlias("std::shared_ptr<vineyard::RecordBatch>") shared_ptr<RecordBatch> batch);
    }
}
