// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.shared_ptr;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::ScalarBaseBuilder")
@FFIGen
@CXXHead("basic/ds/scalar.vineyard.h")
public interface ScalarBaseBuilder<T> extends ObjectBuilder, FFIPointer {
    @CXXValue
    @FFITypeAlias("std::shared_ptr<vineyard::Object>")
    shared_ptr<Object> _Seal(@CXXReference Client client);

    @CXXValue
    Status Build(@CXXReference Client client);

    static <T> ScalarBaseBuilder<T> cast(Class<T> __t, final long __foreign_address) {
        try {
            Class<ScalarBaseBuilder<T>> clz = (Class<ScalarBaseBuilder<T>>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(FFITypeFactory.makeParameterizedType(ScalarBaseBuilder.class, __t), true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static <T> ScalarBaseBuilder<T> cast(Class<T> __t, final FFIPointer __foreign_pointer) {
        return ScalarBaseBuilder.cast(__t, __foreign_pointer.getAddress());
    }

    static <T> Factory<T> getFactory(Class<T> __t) {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(FFITypeFactory.makeParameterizedType(ScalarBaseBuilder.class, __t), true));
    }

    static <T> ScalarBaseBuilder<T> create(Class<T> __t, @CXXReference Client client) {
        return ScalarBaseBuilder.getFactory(__t).create(client);
    }

    static <T> ScalarBaseBuilder<T> create(Class<T> __t, @CXXReference Scalar<T> __value) {
        return ScalarBaseBuilder.getFactory(__t).create(__value);
    }

    static <T> ScalarBaseBuilder<T> create(Class<T> __t,
            @CXXReference shared_ptr<Scalar<T>> __value) {
        return ScalarBaseBuilder.getFactory(__t).create(__value);
    }

    @FFIFactory
    @CXXHead("basic/ds/scalar.vineyard.h")
    interface Factory<T> {
        ScalarBaseBuilder<T> create(@CXXReference Client client);

        ScalarBaseBuilder<T> create(@CXXReference Scalar<T> __value);

        ScalarBaseBuilder<T> create(@CXXReference shared_ptr<Scalar<T>> __value);
    }
}
