// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.shared_ptr;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::SequenceBaseBuilder")
@FFIGen
@CXXHead("basic/ds/sequence.vineyard.h")
public interface SequenceBaseBuilder extends ObjectBuilder, FFIPointer {
    @CXXValue
    @FFITypeAlias("std::shared_ptr<vineyard::Object>")
    shared_ptr<Object> _Seal(@CXXReference Client client);

    @CXXValue
    Status Build(@CXXReference Client client);

    static SequenceBaseBuilder cast(final long __foreign_address) {
        try {
            Class<SequenceBaseBuilder> clz = (Class<SequenceBaseBuilder>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(SequenceBaseBuilder.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static SequenceBaseBuilder cast(final FFIPointer __foreign_pointer) {
        return SequenceBaseBuilder.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(SequenceBaseBuilder.class, true));
    }

    static SequenceBaseBuilder create(@CXXReference Client client) {
        return SequenceBaseBuilder.getFactory().create(client);
    }

    static SequenceBaseBuilder create(@CXXReference Sequence __value) {
        return SequenceBaseBuilder.getFactory().create(__value);
    }

    static SequenceBaseBuilder create(
            @CXXReference @FFITypeAlias("const std::shared_ptr<vineyard::Sequence>") shared_ptr<Sequence> __value) {
        return SequenceBaseBuilder.getFactory().create(__value);
    }

    @FFIFactory
    @CXXHead("basic/ds/sequence.vineyard.h")
    interface Factory {
        SequenceBaseBuilder create(@CXXReference Client client);

        SequenceBaseBuilder create(@CXXReference Sequence __value);

        SequenceBaseBuilder create(
                @CXXReference @FFITypeAlias("const std::shared_ptr<vineyard::Sequence>") shared_ptr<Sequence> __value);
    }
}
