// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard;

import com.alibaba.fastffi.CXXEnum;
import com.alibaba.fastffi.CXXEnumMap;
import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIGetter;
import com.alibaba.fastffi.FFILibrary;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import com.alibaba.fastffi.FFITypeRefiner;
import io.v6d.std.CInt;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::StreamOpenMode")
@FFITypeRefiner("io.v6d.vineyard.StreamOpenMode.get")
@CXXHead("client/client_base.h")
public enum StreamOpenMode implements CXXEnum {
    read(Library.INSTANCE.read()),

    write(Library.INSTANCE.write());

    private static final CXXEnumMap<StreamOpenMode> $map = new CXXEnumMap<>(values());

    int $value;

    StreamOpenMode(int value) {
        $value = value;
    }

    StreamOpenMode(CInt value) {
        $value = value.get();
    }

    public static StreamOpenMode get(int value) {
        return $map.get(value);
    }

    public static StreamOpenMode get(CInt value) {
        return $map.get(value.get());
    }

    public int getValue() {
        return $value;
    }

    public static StreamOpenMode cast(final long __foreign_address) {
        try {
            Class<StreamOpenMode> clz = (Class<StreamOpenMode>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(StreamOpenMode.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    public static StreamOpenMode cast(final FFIPointer __foreign_pointer) {
        return StreamOpenMode.cast(__foreign_pointer.getAddress());
    }

    @FFIGen
    @FFILibrary(
            value = "vineyard::StreamOpenMode",
            namespace = "vineyard::StreamOpenMode"
    )
    @CXXHead("client/client_base.h")
    public interface Library {
        Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

        @FFIGetter
        int read();

        @FFIGetter
        int write();
    }
}
