# Copyright 2020-2023 Alibaba Group Holding Limited.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    app.vineyard.io/name: {{ .Name }}
    app.kubernetes.io/instance: {{ .Namespace -}} - {{- .Name }}
    app.kubernetes.io/component: deployment
spec:
  replicas: {{ .Spec.Replicas }}
  selector:
    matchLabels:
      app.vineyard.io/name: {{ .Name }}
      app.kubernetes.io/name: {{ .Name }}
      app.kubernetes.io/instance: {{ .Namespace -}} - {{- .Name }}
  template:
    metadata:
      labels:
        app.vineyard.io/role: vineyardd
        app.vineyard.io/name: {{ .Name }}
        app.kubernetes.io/name: {{ .Name }}
        app.kubernetes.io/instance: {{ .Namespace -}} - {{- .Name }}
        app.kubernetes.io/component: deployment
      annotations:
        kubectl.kubernetes.io/default-container: "vineyardd"
        kubectl.kubernetes.io/default-logs-container: "vineyardd"
    spec:
      containers:
        - name: vineyardd
          image: {{ .Spec.Vineyard.Image }}
          imagePullPolicy: {{ .Spec.Vineyard.ImagePullPolicy }}
{{- if .Spec.SecurityContext }}
          securityContext:
{{ toYaml .Spec.SecurityContext | indent 12 }}
{{- end }}
          command:
          - /bin/bash
          - -c
          - >
            /usr/local/bin/vineyardd
            --sync_crds {{ .Spec.Vineyard.SyncCRDs }}
            {{- if .Spec.Volume.MountPath }}
            --socket {{ .Spec.Volume.MountPath }}/vineyard.sock
            {{- else }}
            --socket /var/run/vineyard.sock
            {{- end }}
            --size {{ .Spec.Vineyard.Size }}
            {{- if .Spec.Vineyard.ReserveMemory }}
            --reserve_memory
            {{- end }}
            --stream_threshold {{ .Spec.Vineyard.StreamThreshold }}
            --etcd_cmd etcd
            --etcd_prefix /vineyard
            --etcd_endpoint http://{{ .Name }}-etcd-service:2379
            {{- if .Spec.Vineyard.Spill.Path }}
            --spill_path {{ .Spec.Vineyard.Spill.Path }}
            --spill_lower_rate {{ .Spec.Vineyard.Spill.SpillLowerRate }}
            --spill_upper_rate {{ .Spec.Vineyard.Spill.SpillUpperRate }}
            {{- end }}
            {{- if .Spec.Metric.Enable }}
            --metrics
            -log_dir /var/log/vineyard/
            {{- end }}
          env:
          - name: VINEYARDD_UID
            value: {{ .UID }}
          - name: VINEYARDD_NAME
            value: {{ .Name }}
          - name: VINEYARDD_NAMESPACE
            value: {{ .Namespace }}
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: USER
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          {{range .Spec.Vineyard.Env}}
          - name: {{ .Name }}
            value: {{ .Value }}
          {{end}}
          ports:
            - name: rpc
              containerPort: 9600
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9600
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
              - ls
              {{- if .Spec.Volume.MountPath }}
              - {{ .Spec.Volume.MountPath }}/vineyard.sock
              {{- else }}
              - /var/run/vineyard.sock
              {{- end }}
          volumeMounts:
          {{- if .Spec.Volume.MountPath }}
          - name: vineyard-socket
            mountPath: {{ .Spec.Volume.MountPath }}
          {{- else }}
          - name: vineyard-socket
            mountPath: /var/run
          {{- end }}
{{- if .Spec.VolumeMounts }}
{{ toYaml .Spec.VolumeMounts | indent 10 }}
{{- end }}
          {{- if .Spec.Vineyard.Spill.Name }}
          - name: {{ .Spec.Vineyard.Spill.Name }}
            mountPath: {{ .Spec.Vineyard.Spill.Path }}
          {{- end }}
          - name: shm
            mountPath: /dev/shm
          - name: log
            mountPath: /var/log/vineyard
          resources:
            requests:
              {{- if .Spec.Vineyard.CPU }}
              cpu: "{{ .Spec.Vineyard.CPU }}"
              {{- end }}
              {{- if .Spec.Vineyard.Memory }}
              memory: "{{ .Spec.Vineyard.Memory }}"
              {{- end }}
            limits:
              {{- if .Spec.Vineyard.CPU }}
              cpu: "{{ .Spec.Vineyard.CPU }}"
              {{- end }}
              {{- if .Spec.Vineyard.Memory }}
              memory: "{{ .Spec.Vineyard.Memory }}"
              {{- end }}
        {{- if .Spec.Metric.Enable }}
        - name: metrics
          image : {{ .Spec.Metric.Image }}
          imagePullPolicy: {{ .Spec.Metric.ImagePullPolicy }}
          command: ["./grok_exporter"]
          args: ["-config", "grok_exporter.yml", "-disable-exporter-metrics", "&"]
          ports:
            - name: exporter
              containerPort: 9144
              protocol: TCP
          volumeMounts:
          - name: log
            mountPath: /var/log/vineyard
        {{- end }}
      volumes:
      {{- if .Spec.Volume.PvcName }}
      - name: vineyard-socket
        persistentVolumeClaim:
          claimName: {{ .Spec.Volume.PvcName }}
      {{- else }}
      - name: vineyard-socket
        hostPath:
          path: {{ .Spec.Vineyard.Socket }}
      {{- end }}
{{- if .Spec.Volumes }}
{{ toYaml .Spec.Volumes | indent 6 }}
{{- end }}
      {{- if .Spec.Vineyard.Spill.Name }}
      - name: {{ .Spec.Vineyard.Spill.Name }}
        persistentVolumeClaim:
          claimName: {{ .Spec.Vineyard.Spill.Name }}
      {{- end }}
      - name: shm
        emptyDir:
          medium: Memory
      - name: log
        emptyDir: {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                     - {{ .Namespace -}} - {{- .Name }}
              topologyKey: "kubernetes.io/hostname"
