// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.vineyard.impl.numericarraybuilder;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.arrow.ArrayData;
import io.v6d.arrow.Buffer;
import io.v6d.arrow.DataType;
import io.v6d.arrow.impl.numericarray.IteratorTypeArrowUInt64Type;
import io.v6d.arrow.impl.numericarray.ValueTypeArrowUInt64Type;
import io.v6d.std.shared_ptr;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("vineyard::NumericArrayBuilder<unsigned long long>::ArrayType")
@FFIGen
@CXXHead("basic/ds/arrow.h")
public interface ArrayTypeUnsignedLongLong extends CXXPointer {
    @FFIExpr("{0}")
    io.v6d.vineyard.impl.converttoarrowtype.ArrayTypeUnsignedLongLong get();

    ValueTypeArrowUInt64Type raw_values();

    long Value(long i);

    long GetView(long i);

    @CXXValue
    IteratorTypeArrowUInt64Type begin();

    @CXXValue
    IteratorTypeArrowUInt64Type end();

    static ArrayTypeUnsignedLongLong cast(final long __foreign_address) {
        try {
            Class<ArrayTypeUnsignedLongLong> clz = (Class<ArrayTypeUnsignedLongLong>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(ArrayTypeUnsignedLongLong.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static ArrayTypeUnsignedLongLong cast(final FFIPointer __foreign_pointer) {
        return ArrayTypeUnsignedLongLong.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(ArrayTypeUnsignedLongLong.class, true));
    }

    static ArrayTypeUnsignedLongLong create(
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::ArrayData>") shared_ptr<ArrayData> data) {
        return ArrayTypeUnsignedLongLong.getFactory().create(data);
    }

    static ArrayTypeUnsignedLongLong create(
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::DataType>") shared_ptr<DataType> arg0,
            long arg1,
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::Buffer>") shared_ptr<Buffer> arg2,
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::Buffer>") shared_ptr<Buffer> arg3,
            long arg4, long arg5) {
        return ArrayTypeUnsignedLongLong.getFactory().create(arg0, arg1, arg2, arg3, arg4, arg5);
    }

    @FFIFactory
    @CXXHead("basic/ds/arrow.h")
    interface Factory {
        ArrayTypeUnsignedLongLong create(
                @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::ArrayData>") shared_ptr<ArrayData> data);

        ArrayTypeUnsignedLongLong create(
                @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::DataType>") shared_ptr<DataType> arg0,
                long arg1,
                @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::Buffer>") shared_ptr<Buffer> arg2,
                @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::Buffer>") shared_ptr<Buffer> arg3,
                long arg4, long arg5);
    }
}
