// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.std.impl.basic_string;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.CChar;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("std::basic_string<char, std::char_traits<char>, std::allocator<char>>::const_reference")
@FFIGen
@CXXHead(
        system = "string"
)
public interface ConstReferenceCharStdCharTraitsCharStdAllocatorChar extends CXXPointer {
    @FFIExpr("(*{0})")
    CChar get();

    @FFIExpr("*{0} = (std::basic_string<char, std::char_traits<char>, std::allocator<char>>::const_reference){1}")
    void set(CChar __value);

    static ConstReferenceCharStdCharTraitsCharStdAllocatorChar cast(final long __foreign_address) {
        try {
            Class<ConstReferenceCharStdCharTraitsCharStdAllocatorChar> clz = (Class<ConstReferenceCharStdCharTraitsCharStdAllocatorChar>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(ConstReferenceCharStdCharTraitsCharStdAllocatorChar.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static ConstReferenceCharStdCharTraitsCharStdAllocatorChar cast(
            final FFIPointer __foreign_pointer) {
        return ConstReferenceCharStdCharTraitsCharStdAllocatorChar.cast(__foreign_pointer.getAddress());
    }
}
