// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow.detail.impl.ctypeimpl;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::detail::CTypeImpl<arrow::FloatType, arrow::FloatingPointType, 11, float>::c_type")
@FFIGen
@CXXHead(
        system = "arrow/type.h"
)
public interface CTypeArrowFloatTypeArrowFloatingPointType11Float extends CXXPointer {
    @FFIExpr("(*{0})")
    float get();

    @FFIExpr("*{0} = (arrow::detail::CTypeImpl<arrow::FloatType, arrow::FloatingPointType, 11, float>::c_type){1}")
    void set(float __value);

    static CTypeArrowFloatTypeArrowFloatingPointType11Float cast(final long __foreign_address) {
        try {
            Class<CTypeArrowFloatTypeArrowFloatingPointType11Float> clz = (Class<CTypeArrowFloatTypeArrowFloatingPointType11Float>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(CTypeArrowFloatTypeArrowFloatingPointType11Float.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static CTypeArrowFloatTypeArrowFloatingPointType11Float cast(
            final FFIPointer __foreign_pointer) {
        return CTypeArrowFloatTypeArrowFloatingPointType11Float.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(CTypeArrowFloatTypeArrowFloatingPointType11Float.class, true));
    }

    static CTypeArrowFloatTypeArrowFloatingPointType11Float create() {
        return CTypeArrowFloatTypeArrowFloatingPointType11Float.getFactory().create();
    }

    static CTypeArrowFloatTypeArrowFloatingPointType11Float create(float __value) {
        return CTypeArrowFloatTypeArrowFloatingPointType11Float.getFactory().create(__value);
    }

    @FFIFactory
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Factory {
        CTypeArrowFloatTypeArrowFloatingPointType11Float create();

        CTypeArrowFloatTypeArrowFloatingPointType11Float create(float __value);
    }
}
