// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow.detail.impl.ctypeimpl;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::detail::CTypeImpl<arrow::Int64Type, arrow::IntegerType, 9, long long>::c_type")
@FFIGen
@CXXHead(
        system = "arrow/type.h"
)
public interface CTypeArrowInt64TypeArrowIntegerType9LongLong extends CXXPointer {
    @FFIExpr("(*{0})")
    long get();

    @FFIExpr("*{0} = (arrow::detail::CTypeImpl<arrow::Int64Type, arrow::IntegerType, 9, long long>::c_type){1}")
    void set(long __value);

    static CTypeArrowInt64TypeArrowIntegerType9LongLong cast(final long __foreign_address) {
        try {
            Class<CTypeArrowInt64TypeArrowIntegerType9LongLong> clz = (Class<CTypeArrowInt64TypeArrowIntegerType9LongLong>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(CTypeArrowInt64TypeArrowIntegerType9LongLong.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static CTypeArrowInt64TypeArrowIntegerType9LongLong cast(final FFIPointer __foreign_pointer) {
        return CTypeArrowInt64TypeArrowIntegerType9LongLong.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(CTypeArrowInt64TypeArrowIntegerType9LongLong.class, true));
    }

    static CTypeArrowInt64TypeArrowIntegerType9LongLong create() {
        return CTypeArrowInt64TypeArrowIntegerType9LongLong.getFactory().create();
    }

    static CTypeArrowInt64TypeArrowIntegerType9LongLong create(long __value) {
        return CTypeArrowInt64TypeArrowIntegerType9LongLong.getFactory().create(__value);
    }

    @FFIFactory
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Factory {
        CTypeArrowInt64TypeArrowIntegerType9LongLong create();

        CTypeArrowInt64TypeArrowIntegerType9LongLong create(long __value);
    }
}
