// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow.detail.impl.ctypeimpl;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::detail::CTypeImpl<arrow::Int16Type, arrow::IntegerType, 5, short>::c_type")
@FFIGen
@CXXHead(
        system = "arrow/type.h"
)
public interface CTypeArrowInt16TypeArrowIntegerType5Short extends CXXPointer {
    @FFIExpr("(*{0})")
    short get();

    @FFIExpr("*{0} = (arrow::detail::CTypeImpl<arrow::Int16Type, arrow::IntegerType, 5, short>::c_type){1}")
    void set(short __value);

    static CTypeArrowInt16TypeArrowIntegerType5Short cast(final long __foreign_address) {
        try {
            Class<CTypeArrowInt16TypeArrowIntegerType5Short> clz = (Class<CTypeArrowInt16TypeArrowIntegerType5Short>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(CTypeArrowInt16TypeArrowIntegerType5Short.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static CTypeArrowInt16TypeArrowIntegerType5Short cast(final FFIPointer __foreign_pointer) {
        return CTypeArrowInt16TypeArrowIntegerType5Short.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(CTypeArrowInt16TypeArrowIntegerType5Short.class, true));
    }

    static CTypeArrowInt16TypeArrowIntegerType5Short create() {
        return CTypeArrowInt16TypeArrowIntegerType5Short.getFactory().create();
    }

    static CTypeArrowInt16TypeArrowIntegerType5Short create(short __value) {
        return CTypeArrowInt16TypeArrowIntegerType5Short.getFactory().create(__value);
    }

    @FFIFactory
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Factory {
        CTypeArrowInt16TypeArrowIntegerType5Short create();

        CTypeArrowInt16TypeArrowIntegerType5Short create(short __value);
    }
}
