#
#include "../include/topology/adjacentlist.h"
#include "../include/topology/edgelist.h"
#include "../include/topology/structure.h"
#include "../include/topology/vertexlist.h"
#include "../include/partition/partition.h"
#include "../include/partition/reference.h"
#include "../include/partition/topology.h"
#include "../include/property/partition.h"
#include "../include/property/primarykey.h"
#include "../include/property/property.h"
#include "../include/property/propertylist.h"
#include "../include/property/propertytable.h"
#include "../include/property/topology.h"
#include "../include/property/type.h"
#include "../include/index/label.h"
#include "../include/index/order.h"