// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow.impl.numericbuilder;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.arrow.ArrayData;
import io.v6d.arrow.impl.numericarray.IteratorTypeArrowDoubleType;
import io.v6d.arrow.impl.numericarray.ValueTypeArrowDoubleType;
import io.v6d.std.shared_ptr;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::NumericBuilder<arrow::DoubleType>::ArrayType")
@FFIGen
@CXXHead(
        system = "arrow/array/builder_primitive.h"
)
public interface ArrayTypeArrowDoubleType extends CXXPointer {
    @FFIExpr("{0}")
    io.v6d.arrow.impl.typetraits.ArrayTypeArrowDoubleType get();

    ValueTypeArrowDoubleType raw_values();

    double Value(long i);

    double GetView(long i);

    @CXXValue
    IteratorTypeArrowDoubleType begin();

    @CXXValue
    IteratorTypeArrowDoubleType end();

    static ArrayTypeArrowDoubleType cast(final long __foreign_address) {
        try {
            Class<ArrayTypeArrowDoubleType> clz = (Class<ArrayTypeArrowDoubleType>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(ArrayTypeArrowDoubleType.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static ArrayTypeArrowDoubleType cast(final FFIPointer __foreign_pointer) {
        return ArrayTypeArrowDoubleType.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(ArrayTypeArrowDoubleType.class, true));
    }

    static ArrayTypeArrowDoubleType create(
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::ArrayData>") shared_ptr<ArrayData> data) {
        return ArrayTypeArrowDoubleType.getFactory().create(data);
    }

    @FFIFactory
    @CXXHead(
            system = "arrow/array/builder_primitive.h"
    )
    interface Factory {
        ArrayTypeArrowDoubleType create(
                @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::ArrayData>") shared_ptr<ArrayData> data);
    }
}
