// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow.impl.numericbuilder;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.arrow.detail.impl.ctypeimpl.CTypeArrowUInt64TypeArrowIntegerType8UnsignedLongLong;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::NumericBuilder<arrow::UInt64Type>::value_type")
@FFIGen
@CXXHead(
        system = "arrow/array/builder_primitive.h"
)
public interface ValueTypeArrowUInt64Type extends CXXPointer {
    @FFIExpr("{0}")
    CTypeArrowUInt64TypeArrowIntegerType8UnsignedLongLong get();

    static ValueTypeArrowUInt64Type cast(final long __foreign_address) {
        try {
            Class<ValueTypeArrowUInt64Type> clz = (Class<ValueTypeArrowUInt64Type>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(ValueTypeArrowUInt64Type.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static ValueTypeArrowUInt64Type cast(final FFIPointer __foreign_pointer) {
        return ValueTypeArrowUInt64Type.cast(__foreign_pointer.getAddress());
    }
}
