// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.std.impl.__wrap_iter;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.CChar;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("std::__wrap_iter<char*>::iterator_type")
@FFIGen
@CXXHead(
        system = "__iterator/wrap_iter.h"
)
public interface IteratorTypeChar extends CXXPointer {
    @FFIExpr("(*{0})")
    CChar get();

    @FFIExpr("*{0} = (std::__wrap_iter<char*>::iterator_type){1}")
    void set(CChar __value);

    static IteratorTypeChar cast(final long __foreign_address) {
        try {
            Class<IteratorTypeChar> clz = (Class<IteratorTypeChar>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(IteratorTypeChar.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static IteratorTypeChar cast(final FFIPointer __foreign_pointer) {
        return IteratorTypeChar.cast(__foreign_pointer.getAddress());
    }
}
