// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow.io;

import com.alibaba.fastffi.CXXEnum;
import com.alibaba.fastffi.CXXEnumMap;
import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIGetter;
import com.alibaba.fastffi.FFILibrary;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import com.alibaba.fastffi.FFITypeRefiner;
import io.v6d.std.CInt;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::io::FileMode")
@FFIGen
@CXXHead(
        system = "arrow/io/type_fwd.h"
)
public interface FileMode extends FFIPointer {
    static FileMode cast(final long __foreign_address) {
        try {
            Class<FileMode> clz = (Class<FileMode>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(FileMode.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static FileMode cast(final FFIPointer __foreign_pointer) {
        return FileMode.cast(__foreign_pointer.getAddress());
    }

    @FFITypeAlias("arrow::io::FileMode::type")
    @FFITypeRefiner("io.v6d.arrow.io.FileMode.type.get")
    @CXXHead(
            system = "arrow/io/type_fwd.h"
    )
    enum type implements CXXEnum {
        READ(Library.INSTANCE.READ()),

        WRITE(Library.INSTANCE.WRITE()),

        READWRITE(Library.INSTANCE.READWRITE());

        private static final CXXEnumMap<type> $map = new CXXEnumMap<>(values());

        int $value;

        type(int value) {
            $value = value;
        }

        type(CInt value) {
            $value = value.get();
        }

        public static type get(int value) {
            return $map.get(value);
        }

        public static type get(CInt value) {
            return $map.get(value.get());
        }

        public int getValue() {
            return $value;
        }

        public static type cast(final long __foreign_address) {
            try {
                Class<type> clz = (Class<type>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(type.class, true));
                return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
                return null;
            }
        }

        public static type cast(final FFIPointer __foreign_pointer) {
            return type.cast(__foreign_pointer.getAddress());
        }

        @FFIGen
        @FFILibrary(
                value = "arrow::io::FileMode::type",
                namespace = "arrow::io::FileMode::type"
        )
        @CXXHead(
                system = "arrow/io/type_fwd.h"
        )
        public interface Library {
            Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

            @FFIGetter
            int READ();

            @FFIGetter
            int WRITE();

            @FFIGetter
            int READWRITE();
        }
    }
}
