// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow.io;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIGetter;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::io::ReadRange")
@FFIGen
@CXXHead(
        system = "arrow/io/interfaces.h"
)
public interface ReadRange extends FFIPointer {
    @FFIGetter
    long offset();

    @FFIGetter
    long length();

    boolean Contains(@CXXReference ReadRange other);

    static ReadRange cast(final long __foreign_address) {
        try {
            Class<ReadRange> clz = (Class<ReadRange>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(ReadRange.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static ReadRange cast(final FFIPointer __foreign_pointer) {
        return ReadRange.cast(__foreign_pointer.getAddress());
    }
}
