// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow.impl.numericarray;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.arrow.Date64Type;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::NumericArray<arrow::Date64Type>::value_type")
@FFIGen
@CXXHead(
        system = "arrow/array/array_primitive.h"
)
public interface ValueTypeArrowDate64Type extends CXXPointer {
    @FFIExpr("{0}")
    Date64Type.c_type get();

    static ValueTypeArrowDate64Type cast(final long __foreign_address) {
        try {
            Class<ValueTypeArrowDate64Type> clz = (Class<ValueTypeArrowDate64Type>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(ValueTypeArrowDate64Type.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static ValueTypeArrowDate64Type cast(final FFIPointer __foreign_pointer) {
        return ValueTypeArrowDate64Type.cast(__foreign_pointer.getAddress());
    }
}
