// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.shared_ptr;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::BaseListType")
@FFIGen
@CXXHead(
        system = "arrow/type.h"
)
public interface BaseListType extends NestedType, FFIPointer {
    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Field>")
    shared_ptr<Field> value_field();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::DataType>")
    shared_ptr<DataType> value_type();

    static BaseListType cast(final long __foreign_address) {
        try {
            Class<BaseListType> clz = (Class<BaseListType>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(BaseListType.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static BaseListType cast(final FFIPointer __foreign_pointer) {
        return BaseListType.cast(__foreign_pointer.getAddress());
    }
}
