// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIGetter;
import com.alibaba.fastffi.FFILibrary;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.CChar;
import io.v6d.std.string;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::DayTimeIntervalType")
@FFIGen
@CXXHead(
        system = "arrow/type.h"
)
public interface DayTimeIntervalType extends IntervalType, FFIPointer {
    @CXXValue
    @FFITypeAlias("arrow::IntervalType::type")
    IntervalType.type interval_type();

    int bit_width();

    @CXXValue
    string ToString();

    @CXXValue
    string name();

    static DayTimeIntervalType cast(final long __foreign_address) {
        try {
            Class<DayTimeIntervalType> clz = (Class<DayTimeIntervalType>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(DayTimeIntervalType.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static DayTimeIntervalType cast(final FFIPointer __foreign_pointer) {
        return DayTimeIntervalType.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(DayTimeIntervalType.class, true));
    }

    static DayTimeIntervalType create() {
        return DayTimeIntervalType.getFactory().create();
    }

    @FFIFactory
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Factory {
        DayTimeIntervalType create();
    }

    @FFIGen
    @FFILibrary(
            value = "arrow::DayTimeIntervalType",
            namespace = "arrow::DayTimeIntervalType"
    )
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Library {
        Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

        CChar type_name();
    }

    @FFITypeAlias("arrow::DayTimeIntervalType::DayMilliseconds")
    @FFIGen
    @CXXHead(
            system = "arrow/type.h"
    )
    interface DayMilliseconds extends FFIPointer {
        @FFIGetter
        int days();

        @FFIGetter
        int milliseconds();

        static DayMilliseconds cast(final long __foreign_address) {
            try {
                Class<DayMilliseconds> clz = (Class<DayMilliseconds>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(DayMilliseconds.class, true));
                return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
                return null;
            }
        }

        static DayMilliseconds cast(final FFIPointer __foreign_pointer) {
            return DayMilliseconds.cast(__foreign_pointer.getAddress());
        }

        static Factory getFactory() {
            return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(DayMilliseconds.class, true));
        }

        static DayMilliseconds create(int days, int milliseconds) {
            return DayMilliseconds.getFactory().create(days, milliseconds);
        }

        @FFIFactory
        @CXXHead(
                system = "arrow/type.h"
        )
        interface Factory {
            DayMilliseconds create(int days, int milliseconds);
        }
    }

    @FFITypeAlias("arrow::DayTimeIntervalType::c_type")
    @FFIGen
    @CXXHead(
            system = "arrow/type.h"
    )
    interface c_type extends CXXPointer {
        @FFIExpr("{0}")
        DayMilliseconds get();

        @FFIGetter
        int days();

        @FFIGetter
        int milliseconds();

        static c_type cast(final long __foreign_address) {
            try {
                Class<c_type> clz = (Class<c_type>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(c_type.class, true));
                return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
                return null;
            }
        }

        static c_type cast(final FFIPointer __foreign_pointer) {
            return c_type.cast(__foreign_pointer.getAddress());
        }

        static Factory getFactory() {
            return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(c_type.class, true));
        }

        static c_type create(int days, int milliseconds) {
            return c_type.getFactory().create(days, milliseconds);
        }

        @FFIFactory
        @CXXHead(
                system = "arrow/type.h"
        )
        interface Factory {
            c_type create(int days, int milliseconds);
        }
    }

    @FFITypeAlias("arrow::DayTimeIntervalType::PhysicalType")
    @FFIGen
    @CXXHead(
            system = "arrow/type.h"
    )
    interface PhysicalType extends CXXPointer {
        @FFIExpr("{0}")
        DayTimeIntervalType get();

        @CXXValue
        @FFITypeAlias("arrow::IntervalType::type")
        IntervalType.type interval_type();

        int bit_width();

        @CXXValue
        string ToString();

        @CXXValue
        string name();

        static PhysicalType cast(final long __foreign_address) {
            try {
                Class<PhysicalType> clz = (Class<PhysicalType>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(PhysicalType.class, true));
                return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
                return null;
            }
        }

        static PhysicalType cast(final FFIPointer __foreign_pointer) {
            return PhysicalType.cast(__foreign_pointer.getAddress());
        }

        static Factory getFactory() {
            return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(PhysicalType.class, true));
        }

        static PhysicalType create() {
            return PhysicalType.getFactory().create();
        }

        @FFIFactory
        @CXXHead(
                system = "arrow/type.h"
        )
        interface Factory {
            PhysicalType create();
        }

        @FFIGen
        @FFILibrary(
                value = "arrow::DayTimeIntervalType",
                namespace = "arrow::DayTimeIntervalType"
        )
        @CXXHead(
                system = "arrow/type.h"
        )
        interface Library {
            Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

            CChar type_name();
        }
    }
}
