// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFILibrary;
import com.alibaba.fastffi.FFINameAlias;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.CChar;
import io.v6d.std.CInt;
import io.v6d.std.CSignedChar;
import io.v6d.std.shared_ptr;
import io.v6d.std.string;
import io.v6d.std.vector;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::DenseUnionArray")
@FFIGen
@CXXHead(
        system = "arrow/array/array_nested.h"
)
public interface DenseUnionArray extends UnionArray, FFIPointer {
    @FFINameAlias("union_type")
    DenseUnionType union_type_1();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Buffer>")
    shared_ptr<Buffer> value_offsets();

    int value_offset(long i);

    CInt raw_value_offsets();

    static DenseUnionArray cast(final long __foreign_address) {
        try {
            Class<DenseUnionArray> clz = (Class<DenseUnionArray>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(DenseUnionArray.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static DenseUnionArray cast(final FFIPointer __foreign_pointer) {
        return DenseUnionArray.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(DenseUnionArray.class, true));
    }

    static DenseUnionArray create(
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::ArrayData>") shared_ptr<ArrayData> data) {
        return DenseUnionArray.getFactory().create(data);
    }

    static DenseUnionArray create(
            @CXXValue @FFITypeAlias("std::shared_ptr<arrow::DataType>") shared_ptr<DataType> type,
            long length, @CXXValue ArrayVector children,
            @CXXValue @FFITypeAlias("std::shared_ptr<arrow::Buffer>") shared_ptr<Buffer> type_ids,
            @CXXValue @FFITypeAlias("std::shared_ptr<arrow::Buffer>") shared_ptr<Buffer> value_offsets,
            long offset) {
        return DenseUnionArray.getFactory().create(type, length, children, type_ids, value_offsets, offset);
    }

    @FFIFactory
    @CXXHead(
            system = "arrow/array/array_nested.h"
    )
    interface Factory {
        DenseUnionArray create(
                @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::ArrayData>") shared_ptr<ArrayData> data);

        DenseUnionArray create(
                @CXXValue @FFITypeAlias("std::shared_ptr<arrow::DataType>") shared_ptr<DataType> type,
                long length, @CXXValue ArrayVector children,
                @CXXValue @FFITypeAlias("std::shared_ptr<arrow::Buffer>") shared_ptr<Buffer> type_ids,
                @CXXValue @FFITypeAlias("std::shared_ptr<arrow::Buffer>") shared_ptr<Buffer> value_offsets,
                long offset);
    }

    @FFIGen
    @FFILibrary(
            value = "arrow::DenseUnionArray",
            namespace = "arrow::DenseUnionArray"
    )
    @CXXHead(
            system = "arrow/array/array_nested.h"
    )
    interface Library {
        Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

        @CXXValue
        @FFITypeAlias("arrow::Result<std::shared_ptr<arrow::Array>>")
        Result<shared_ptr<Array>> Make(@CXXReference Array type_ids,
                @CXXReference Array value_offsets, @CXXValue ArrayVector children,
                @CXXValue @FFITypeAlias("std::vector<signed char>") vector<CSignedChar> type_codes);

        @CXXValue
        @FFITypeAlias("arrow::Result<std::shared_ptr<arrow::Array>>")
        Result<shared_ptr<Array>> Make(@CXXReference Array type_ids,
                @CXXReference Array value_offsets, @CXXValue ArrayVector children,
                @CXXValue @FFITypeAlias("std::vector<std::string>") vector<string> field_names,
                @CXXValue @FFITypeAlias("std::vector<signed char>") vector<CSignedChar> type_codes);
    }

    @FFITypeAlias("arrow::DenseUnionArray::TypeClass")
    @FFIGen
    @CXXHead(
            system = "arrow/array/array_nested.h"
    )
    interface TypeClass extends CXXPointer {
        @FFIExpr("{0}")
        DenseUnionType get();

        @CXXValue
        string name();

        static TypeClass cast(final long __foreign_address) {
            try {
                Class<TypeClass> clz = (Class<TypeClass>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(TypeClass.class, true));
                return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
                return null;
            }
        }

        static TypeClass cast(final FFIPointer __foreign_pointer) {
            return TypeClass.cast(__foreign_pointer.getAddress());
        }

        static Factory getFactory() {
            return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(TypeClass.class, true));
        }

        static TypeClass create(
                @CXXValue @FFITypeAlias("std::vector<std::shared_ptr<arrow::Field>>") vector<shared_ptr<Field>> fields,
                @CXXValue @FFITypeAlias("std::vector<signed char>") vector<CSignedChar> type_codes) {
            return TypeClass.getFactory().create(fields, type_codes);
        }

        @FFIFactory
        @CXXHead(
                system = "arrow/array/array_nested.h"
        )
        interface Factory {
            TypeClass create(
                    @CXXValue @FFITypeAlias("std::vector<std::shared_ptr<arrow::Field>>") vector<shared_ptr<Field>> fields,
                    @CXXValue @FFITypeAlias("std::vector<signed char>") vector<CSignedChar> type_codes);
        }

        @FFIGen
        @FFILibrary(
                value = "arrow::DenseUnionType",
                namespace = "arrow::DenseUnionType"
        )
        @CXXHead(
                system = "arrow/array/array_nested.h"
        )
        interface Library {
            Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

            CChar type_name();

            @CXXValue
            @FFITypeAlias("arrow::Result<std::shared_ptr<arrow::DataType>>")
            Result<shared_ptr<DataType>> Make(
                    @CXXValue @FFITypeAlias("std::vector<std::shared_ptr<arrow::Field>>") vector<shared_ptr<Field>> fields,
                    @CXXValue @FFITypeAlias("std::vector<signed char>") vector<CSignedChar> type_codes);
        }
    }
}
