// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFILibrary;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.ostream;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::EqualOptions")
@FFIGen
@CXXHead(
        system = "arrow/compare.h"
)
public interface EqualOptions extends FFIPointer {
    boolean nans_equal();

    @CXXValue
    EqualOptions nans_equal(boolean v);

    double atol();

    @CXXValue
    EqualOptions atol(double v);

    ostream diff_sink();

    @CXXValue
    EqualOptions diff_sink(ostream diff_sink);

    static EqualOptions cast(final long __foreign_address) {
        try {
            Class<EqualOptions> clz = (Class<EqualOptions>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(EqualOptions.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static EqualOptions cast(final FFIPointer __foreign_pointer) {
        return EqualOptions.cast(__foreign_pointer.getAddress());
    }

    @FFIGen
    @FFILibrary(
            value = "arrow::EqualOptions",
            namespace = "arrow::EqualOptions"
    )
    @CXXHead(
            system = "arrow/compare.h"
    )
    interface Library {
        Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

        @CXXValue
        EqualOptions Defaults();
    }
}
