// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIGetter;
import com.alibaba.fastffi.FFILibrary;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.arrow.detail.Fingerprintable;
import io.v6d.std.shared_ptr;
import io.v6d.std.string;
import io.v6d.std.vector;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::Field")
@FFIGen
@CXXHead(
        system = "arrow/type.h"
)
public interface Field extends Fingerprintable, CXXPointer {
    @CXXValue
    @FFITypeAlias("std::shared_ptr<const arrow::KeyValueMetadata>")
    shared_ptr<KeyValueMetadata> metadata();

    boolean HasMetadata();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Field>")
    shared_ptr<Field> WithMetadata(
            @CXXReference @FFITypeAlias("const std::shared_ptr<const arrow::KeyValueMetadata>") shared_ptr<KeyValueMetadata> metadata);

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Field>")
    shared_ptr<Field> WithMergedMetadata(
            @CXXReference @FFITypeAlias("const std::shared_ptr<const arrow::KeyValueMetadata>") shared_ptr<KeyValueMetadata> metadata);

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Field>")
    shared_ptr<Field> RemoveMetadata();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Field>")
    shared_ptr<Field> WithType(
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::DataType>") shared_ptr<DataType> type);

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Field>")
    shared_ptr<Field> WithName(@CXXReference string name);

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Field>")
    shared_ptr<Field> WithNullable(boolean nullable);

    @CXXValue
    @FFITypeAlias("arrow::Result<std::shared_ptr<arrow::Field>>")
    Result<shared_ptr<Field>> MergeWith(@CXXReference Field other, @CXXValue MergeOptions options);

    @CXXValue
    @FFITypeAlias("arrow::Result<std::shared_ptr<arrow::Field>>")
    Result<shared_ptr<Field>> MergeWith(
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::Field>") shared_ptr<Field> other,
            @CXXValue MergeOptions options);

    @CXXValue
    @FFITypeAlias("std::vector<std::shared_ptr<arrow::Field>>")
    vector<shared_ptr<Field>> Flatten();

    boolean Equals(@CXXReference Field other, boolean check_metadata);

    boolean Equals(
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::Field>") shared_ptr<Field> other,
            boolean check_metadata);

    boolean IsCompatibleWith(@CXXReference Field other);

    boolean IsCompatibleWith(
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::Field>") shared_ptr<Field> other);

    @CXXValue
    string ToString(boolean show_metadata);

    @CXXReference
    string name();

    @CXXReference
    @FFITypeAlias("const std::shared_ptr<arrow::DataType>")
    shared_ptr<DataType> type();

    boolean nullable();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Field>")
    shared_ptr<Field> Copy();

    static Field cast(final long __foreign_address) {
        try {
            Class<Field> clz = (Class<Field>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(Field.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static Field cast(final FFIPointer __foreign_pointer) {
        return Field.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(Field.class, true));
    }

    static Field create(@CXXValue string name,
            @CXXValue @FFITypeAlias("std::shared_ptr<arrow::DataType>") shared_ptr<DataType> type,
            boolean nullable,
            @CXXValue @FFITypeAlias("std::shared_ptr<const arrow::KeyValueMetadata>") shared_ptr<KeyValueMetadata> metadata) {
        return Field.getFactory().create(name, type, nullable, metadata);
    }

    @FFIFactory
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Factory {
        Field create(@CXXValue string name,
                @CXXValue @FFITypeAlias("std::shared_ptr<arrow::DataType>") shared_ptr<DataType> type,
                boolean nullable,
                @CXXValue @FFITypeAlias("std::shared_ptr<const arrow::KeyValueMetadata>") shared_ptr<KeyValueMetadata> metadata);
    }

    @FFITypeAlias("arrow::Field::MergeOptions")
    @FFIGen
    @CXXHead(
            system = "arrow/type.h"
    )
    interface MergeOptions extends FFIPointer {
        @FFIGetter
        boolean promote_nullability();

        static MergeOptions cast(final long __foreign_address) {
            try {
                Class<MergeOptions> clz = (Class<MergeOptions>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(MergeOptions.class, true));
                return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
                return null;
            }
        }

        static MergeOptions cast(final FFIPointer __foreign_pointer) {
            return MergeOptions.cast(__foreign_pointer.getAddress());
        }

        @FFIGen
        @FFILibrary(
                value = "arrow::Field::MergeOptions",
                namespace = "arrow::Field::MergeOptions"
        )
        @CXXHead(
                system = "arrow/type.h"
        )
        interface Library {
            Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

            @CXXValue
            MergeOptions Defaults();
        }
    }
}
