// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFILibrary;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.CChar;
import io.v6d.std.string;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::LargeBinaryType")
@FFIGen
@CXXHead(
        system = "arrow/type.h"
)
public interface LargeBinaryType extends BaseBinaryType, FFIPointer {
    @CXXValue
    DataTypeLayout layout();

    @CXXValue
    string ToString();

    @CXXValue
    string name();

    static LargeBinaryType cast(final long __foreign_address) {
        try {
            Class<LargeBinaryType> clz = (Class<LargeBinaryType>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(LargeBinaryType.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static LargeBinaryType cast(final FFIPointer __foreign_pointer) {
        return LargeBinaryType.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(LargeBinaryType.class, true));
    }

    static LargeBinaryType create() {
        return LargeBinaryType.getFactory().create();
    }

    @FFIFactory
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Factory {
        LargeBinaryType create();
    }

    @FFIGen
    @FFILibrary(
            value = "arrow::LargeBinaryType",
            namespace = "arrow::LargeBinaryType"
    )
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Library {
        Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

        CChar type_name();
    }

    @FFITypeAlias("arrow::LargeBinaryType::offset_type")
    @FFIGen
    @CXXHead(
            system = "arrow/type.h"
    )
    interface offset_type extends CXXPointer {
        @FFIExpr("(*{0})")
        long get();

        @FFIExpr("*{0} = (arrow::LargeBinaryType::offset_type){1}")
        void set(long __value);

        static offset_type cast(final long __foreign_address) {
            try {
                Class<offset_type> clz = (Class<offset_type>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(offset_type.class, true));
                return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
                return null;
            }
        }

        static offset_type cast(final FFIPointer __foreign_pointer) {
            return offset_type.cast(__foreign_pointer.getAddress());
        }

        static Factory getFactory() {
            return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(offset_type.class, true));
        }

        static offset_type create() {
            return offset_type.getFactory().create();
        }

        static offset_type create(long __value) {
            return offset_type.getFactory().create(__value);
        }

        @FFIFactory
        @CXXHead(
                system = "arrow/type.h"
        )
        interface Factory {
            offset_type create();

            offset_type create(long __value);
        }
    }

    @FFITypeAlias("arrow::LargeBinaryType::PhysicalType")
    @FFIGen
    @CXXHead(
            system = "arrow/type.h"
    )
    interface PhysicalType extends CXXPointer {
        @FFIExpr("{0}")
        LargeBinaryType get();

        @CXXValue
        DataTypeLayout layout();

        @CXXValue
        string ToString();

        @CXXValue
        string name();

        static PhysicalType cast(final long __foreign_address) {
            try {
                Class<PhysicalType> clz = (Class<PhysicalType>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(PhysicalType.class, true));
                return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
                return null;
            }
        }

        static PhysicalType cast(final FFIPointer __foreign_pointer) {
            return PhysicalType.cast(__foreign_pointer.getAddress());
        }

        static Factory getFactory() {
            return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(PhysicalType.class, true));
        }

        static PhysicalType create() {
            return PhysicalType.getFactory().create();
        }

        @FFIFactory
        @CXXHead(
                system = "arrow/type.h"
        )
        interface Factory {
            PhysicalType create();
        }

        @FFIGen
        @FFILibrary(
                value = "arrow::LargeBinaryType",
                namespace = "arrow::LargeBinaryType"
        )
        @CXXHead(
                system = "arrow/type.h"
        )
        interface Library {
            Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

            CChar type_name();
        }
    }
}
