// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFILibrary;
import com.alibaba.fastffi.FFINameAlias;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.CChar;
import io.v6d.std.shared_ptr;
import io.v6d.std.string;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::MapType")
@FFIGen
@CXXHead(
        system = "arrow/type.h"
)
public interface MapType extends ListType, FFIPointer {
    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Field>")
    shared_ptr<Field> key_field();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::DataType>")
    shared_ptr<DataType> key_type();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::Field>")
    shared_ptr<Field> item_field();

    @CXXValue
    @FFITypeAlias("std::shared_ptr<arrow::DataType>")
    shared_ptr<DataType> item_type();

    @CXXValue
    @FFINameAlias("ToString")
    string ToString_1();

    @CXXValue
    @FFINameAlias("name")
    string name_1();

    boolean keys_sorted();

    static MapType cast(final long __foreign_address) {
        try {
            Class<MapType> clz = (Class<MapType>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(MapType.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static MapType cast(final FFIPointer __foreign_pointer) {
        return MapType.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(MapType.class, true));
    }

    static MapType create(
            @CXXValue @FFITypeAlias("std::shared_ptr<arrow::DataType>") shared_ptr<DataType> key_type,
            @CXXValue @FFITypeAlias("std::shared_ptr<arrow::DataType>") shared_ptr<DataType> item_type,
            boolean keys_sorted) {
        return MapType.getFactory().create(key_type, item_type, keys_sorted);
    }

    static MapType create(
            @CXXValue @FFITypeAlias("std::shared_ptr<arrow::Field>") shared_ptr<Field> value_field,
            boolean keys_sorted) {
        return MapType.getFactory().create(value_field, keys_sorted);
    }

    @FFIFactory
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Factory {
        MapType create(
                @CXXValue @FFITypeAlias("std::shared_ptr<arrow::DataType>") shared_ptr<DataType> key_type,
                @CXXValue @FFITypeAlias("std::shared_ptr<arrow::DataType>") shared_ptr<DataType> item_type,
                boolean keys_sorted);

        MapType create(
                @CXXValue @FFITypeAlias("std::shared_ptr<arrow::Field>") shared_ptr<Field> value_field,
                boolean keys_sorted);
    }

    @FFIGen
    @FFILibrary(
            value = "arrow::MapType",
            namespace = "arrow::MapType"
    )
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Library {
        Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

        @FFINameAlias("type_name")
        CChar type_name_1();

        @CXXValue
        @FFITypeAlias("arrow::Result<std::shared_ptr<arrow::DataType>>")
        Result<shared_ptr<DataType>> Make(
                @CXXValue @FFITypeAlias("std::shared_ptr<arrow::Field>") shared_ptr<Field> value_field,
                boolean keys_sorted);
    }
}
