// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFINameAlias;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.impl.vector.AllocatorTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar;
import io.v6d.std.impl.vector.ConstIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar;
import io.v6d.std.impl.vector.ConstReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar;
import io.v6d.std.impl.vector.ConstReverseIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar;
import io.v6d.std.impl.vector.IteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar;
import io.v6d.std.impl.vector.ReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar;
import io.v6d.std.impl.vector.ReverseIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar;
import io.v6d.std.impl.vector.ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar;
import io.v6d.std.initializer_list;
import io.v6d.std.shared_ptr;
import io.v6d.std.vector;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::ScalarVector")
@FFIGen
@CXXHead(
        system = "arrow/type_fwd.h"
)
public interface ScalarVector extends CXXPointer {
    @FFIExpr("{0}")
    vector<shared_ptr<Scalar>> get();

    void assign(long __n,
            @CXXValue ConstReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __u);

    void assign(
            @CXXValue @FFITypeAlias("std::initializer_list<std::vector<std::shared_ptr<arrow::Scalar>, std::allocator<std::shared_ptr<arrow::Scalar>>>::value_type>") initializer_list<ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar> __il);

    @CXXValue
    AllocatorTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar get_allocator();

    @CXXValue
    IteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar begin();

    @CXXValue
    @FFINameAlias("begin")
    ConstIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar begin_1();

    @CXXValue
    IteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar end();

    @CXXValue
    @FFINameAlias("end")
    ConstIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar end_1();

    @CXXValue
    ReverseIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar rbegin();

    @CXXValue
    @FFINameAlias("rbegin")
    ConstReverseIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar rbegin_1();

    @CXXValue
    ReverseIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar rend();

    @CXXValue
    @FFINameAlias("rend")
    ConstReverseIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar rend_1();

    @CXXValue
    ConstIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar cbegin();

    @CXXValue
    ConstIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar cend();

    @CXXValue
    ConstReverseIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar crbegin();

    @CXXValue
    ConstReverseIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar crend();

    long size();

    long capacity();

    boolean empty();

    long max_size();

    void reserve(long __n);

    void shrink_to_fit();

    @CXXValue
    ReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar at(long __n);

    @CXXValue
    @FFINameAlias("at")
    ConstReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar at_1(long __n);

    @CXXValue
    ReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar front();

    @CXXValue
    @FFINameAlias("front")
    ConstReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar front_1();

    @CXXValue
    ReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar back();

    @CXXValue
    @FFINameAlias("back")
    ConstReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar back_1();

    ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar data();

    @FFINameAlias("data")
    ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar data_1();

    void push_back(
            @CXXValue ConstReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __x);

    void pop_back();

    @CXXValue
    IteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar insert(
            @CXXValue ConstIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __position,
            @CXXValue ConstReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __x);

    @CXXValue
    IteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar insert(
            @CXXValue ConstIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __position,
            long __n,
            @CXXValue ConstReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __x);

    @CXXValue
    IteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar insert(
            @CXXValue ConstIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __position,
            @CXXValue @FFITypeAlias("std::initializer_list<std::vector<std::shared_ptr<arrow::Scalar>, std::allocator<std::shared_ptr<arrow::Scalar>>>::value_type>") initializer_list<ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar> __il);

    @CXXValue
    IteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar erase(
            @CXXValue ConstIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __position);

    @CXXValue
    IteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar erase(
            @CXXValue ConstIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __first,
            @CXXValue ConstIteratorStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __last);

    void clear();

    void resize(long __sz);

    void resize(long __sz,
            @CXXValue ConstReferenceStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __x);

    boolean __invariants();

    static ScalarVector cast(final long __foreign_address) {
        try {
            Class<ScalarVector> clz = (Class<ScalarVector>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(ScalarVector.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static ScalarVector cast(final FFIPointer __foreign_pointer) {
        return ScalarVector.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(ScalarVector.class, true));
    }

    static ScalarVector create() {
        return ScalarVector.getFactory().create();
    }

    static ScalarVector create(
            @CXXReference AllocatorTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __a) {
        return ScalarVector.getFactory().create(__a);
    }

    static ScalarVector create(long __n) {
        return ScalarVector.getFactory().create(__n);
    }

    static ScalarVector create(long __n,
            @CXXReference AllocatorTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __a) {
        return ScalarVector.getFactory().create(__n, __a);
    }

    static ScalarVector create(long __n,
            @CXXReference ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __x) {
        return ScalarVector.getFactory().create(__n, __x);
    }

    static ScalarVector create(long __n,
            @CXXReference ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __x,
            @CXXReference AllocatorTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __a) {
        return ScalarVector.getFactory().create(__n, __x, __a);
    }

    static ScalarVector create(
            @CXXValue @FFITypeAlias("std::initializer_list<std::vector<std::shared_ptr<arrow::Scalar>, std::allocator<std::shared_ptr<arrow::Scalar>>>::value_type>") initializer_list<ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar> __il) {
        return ScalarVector.getFactory().create(__il);
    }

    static ScalarVector create(
            @CXXValue @FFITypeAlias("std::initializer_list<std::vector<std::shared_ptr<arrow::Scalar>, std::allocator<std::shared_ptr<arrow::Scalar>>>::value_type>") initializer_list<ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar> __il,
            @CXXReference AllocatorTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __a) {
        return ScalarVector.getFactory().create(__il, __a);
    }

    @FFIFactory
    @CXXHead(
            system = "arrow/type_fwd.h"
    )
    interface Factory {
        ScalarVector create();

        ScalarVector create(
                @CXXReference AllocatorTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __a);

        ScalarVector create(long __n);

        ScalarVector create(long __n,
                @CXXReference AllocatorTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __a);

        ScalarVector create(long __n,
                @CXXReference ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __x);

        ScalarVector create(long __n,
                @CXXReference ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __x,
                @CXXReference AllocatorTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __a);

        ScalarVector create(
                @CXXValue @FFITypeAlias("std::initializer_list<std::vector<std::shared_ptr<arrow::Scalar>, std::allocator<std::shared_ptr<arrow::Scalar>>>::value_type>") initializer_list<ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar> __il);

        ScalarVector create(
                @CXXValue @FFITypeAlias("std::initializer_list<std::vector<std::shared_ptr<arrow::Scalar>, std::allocator<std::shared_ptr<arrow::Scalar>>>::value_type>") initializer_list<ValueTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar> __il,
                @CXXReference AllocatorTypeStdSharedPtrArrowScalarStdAllocatorStdSharedPtrArrowScalar __a);
    }
}
