// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFILibrary;
import com.alibaba.fastffi.FFINameAlias;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.CChar;
import io.v6d.std.string;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::StringType")
@FFIGen
@CXXHead(
        system = "arrow/type.h"
)
public interface StringType extends BinaryType, FFIPointer {
    @CXXValue
    @FFINameAlias("ToString")
    string ToString_1();

    @CXXValue
    @FFINameAlias("name")
    string name_1();

    static StringType cast(final long __foreign_address) {
        try {
            Class<StringType> clz = (Class<StringType>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(StringType.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static StringType cast(final FFIPointer __foreign_pointer) {
        return StringType.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(StringType.class, true));
    }

    static StringType create() {
        return StringType.getFactory().create();
    }

    @FFIFactory
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Factory {
        StringType create();
    }

    @FFIGen
    @FFILibrary(
            value = "arrow::StringType",
            namespace = "arrow::StringType"
    )
    @CXXHead(
            system = "arrow/type.h"
    )
    interface Library {
        Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

        @FFINameAlias("type_name")
        CChar type_name_1();
    }

    @FFITypeAlias("arrow::StringType::PhysicalType")
    @FFIGen
    @CXXHead(
            system = "arrow/type.h"
    )
    interface PhysicalType extends CXXPointer {
        @FFIExpr("{0}")
        BinaryType get();

        @CXXValue
        DataTypeLayout layout();

        @CXXValue
        string ToString();

        @CXXValue
        string name();

        static PhysicalType cast(final long __foreign_address) {
            try {
                Class<PhysicalType> clz = (Class<PhysicalType>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(PhysicalType.class, true));
                return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
            } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
                return null;
            }
        }

        static PhysicalType cast(final FFIPointer __foreign_pointer) {
            return PhysicalType.cast(__foreign_pointer.getAddress());
        }

        static Factory getFactory() {
            return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(PhysicalType.class, true));
        }

        static PhysicalType create() {
            return PhysicalType.getFactory().create();
        }

        @FFIFactory
        @CXXHead(
                system = "arrow/type.h"
        )
        interface Factory {
            PhysicalType create();
        }

        @FFIGen
        @FFILibrary(
                value = "arrow::BinaryType",
                namespace = "arrow::BinaryType"
        )
        @CXXHead(
                system = "arrow/type.h"
        )
        interface Library {
            Library INSTANCE = FFITypeFactory.getLibrary(Library.class);

            CChar type_name();
        }
    }
}
