// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.arrow;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.CXXReference;
import com.alibaba.fastffi.CXXValue;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIFactory;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.arrow.impl.numericarray.IteratorTypeArrowUInt8Type;
import io.v6d.arrow.impl.numericarray.ValueTypeArrowUInt8Type;
import io.v6d.std.shared_ptr;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("arrow::UInt8Array")
@FFIGen
@CXXHead("arrow/array/array_primitive.h")
public interface UInt8Array extends CXXPointer {
    @FFIExpr("{0}")
    NumericArray<UInt8Type> get();

    ValueTypeArrowUInt8Type raw_values();

    char Value(long i);

    char GetView(long i);

    @CXXValue
    IteratorTypeArrowUInt8Type begin();

    @CXXValue
    IteratorTypeArrowUInt8Type end();

    static UInt8Array cast(final long __foreign_address) {
        try {
            Class<UInt8Array> clz = (Class<UInt8Array>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(UInt8Array.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static UInt8Array cast(final FFIPointer __foreign_pointer) {
        return UInt8Array.cast(__foreign_pointer.getAddress());
    }

    static Factory getFactory() {
        return FFITypeFactory.getFactory(FFITypeFactory.getFFITypeName(UInt8Array.class, true));
    }

    static UInt8Array create(
            @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::ArrayData>") shared_ptr<ArrayData> data) {
        return UInt8Array.getFactory().create(data);
    }

    @FFIFactory
    @CXXHead("arrow/array/array_primitive.h")
    interface Factory {
        UInt8Array create(
                @CXXReference @FFITypeAlias("const std::shared_ptr<arrow::ArrayData>") shared_ptr<ArrayData> data);
    }
}
