// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.std.impl.allocator_traits;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.impl.__pointer.TypeCharStdAllocatorCharStdAllocatorChar1;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("std::allocator_traits<std::allocator<char>>::pointer")
@FFIGen
@CXXHead(
        system = "__memory/allocator_traits.h"
)
public interface PointerStdAllocatorChar extends CXXPointer {
    @FFIExpr("{0}")
    TypeCharStdAllocatorCharStdAllocatorChar1 get();

    static PointerStdAllocatorChar cast(final long __foreign_address) {
        try {
            Class<PointerStdAllocatorChar> clz = (Class<PointerStdAllocatorChar>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(PointerStdAllocatorChar.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static PointerStdAllocatorChar cast(final FFIPointer __foreign_pointer) {
        return PointerStdAllocatorChar.cast(__foreign_pointer.getAddress());
    }
}
