// Code generated by alibaba/fastFFI. DO NOT EDIT.
//
package io.v6d.std.impl.allocator_traits;

import com.alibaba.fastffi.CXXHead;
import com.alibaba.fastffi.CXXPointer;
import com.alibaba.fastffi.FFIExpr;
import com.alibaba.fastffi.FFIGen;
import com.alibaba.fastffi.FFIPointer;
import com.alibaba.fastffi.FFITypeAlias;
import com.alibaba.fastffi.FFITypeFactory;
import io.v6d.std.impl.__size_type.TypeStdAllocatorStdSharedPtrArrowScalarLong1;
import java.lang.Class;
import java.lang.ClassNotFoundException;
import java.lang.IllegalAccessException;
import java.lang.InstantiationException;
import java.lang.Long;
import java.lang.NoSuchMethodException;
import java.lang.reflect.InvocationTargetException;

@FFITypeAlias("std::allocator_traits<std::allocator<std::shared_ptr<arrow::Scalar>>>::size_type")
@FFIGen
@CXXHead(
        system = "__memory/allocator_traits.h"
)
public interface SizeTypeStdAllocatorStdSharedPtrArrowScalar extends CXXPointer {
    @FFIExpr("{0}")
    TypeStdAllocatorStdSharedPtrArrowScalarLong1 get();

    static SizeTypeStdAllocatorStdSharedPtrArrowScalar cast(final long __foreign_address) {
        try {
            Class<SizeTypeStdAllocatorStdSharedPtrArrowScalar> clz = (Class<SizeTypeStdAllocatorStdSharedPtrArrowScalar>) FFITypeFactory.getType(FFITypeFactory.getFFITypeName(SizeTypeStdAllocatorStdSharedPtrArrowScalar.class, true));
            return clz.getConstructor(Long.TYPE).newInstance(__foreign_address);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException | InstantiationException | IllegalAccessException e) {
            return null;
        }
    }

    static SizeTypeStdAllocatorStdSharedPtrArrowScalar cast(final FFIPointer __foreign_pointer) {
        return SizeTypeStdAllocatorStdSharedPtrArrowScalar.cast(__foreign_pointer.getAddress());
    }
}
